### ISSUE TITLE
As a Backend  developer I want to enable Java 21 Virtual Threads instead of using Thread Pools 

### ISSUE THREAD

**Issue by sekasx** [ctrl-space-labs/gendox-core#100]
## New Major Version
This is a breaking change. Since this is still in beta, only the minor version will be updated though. 
TBD the exact versioning

### Description

Threads Pools is a major Java new feature, introduced as experimental in Java 19 and maid final in **Java 21** which is the next LTS Java Version.

Virtual Threads have significant benefits over Classic Threads:
- https://foojay.io/today/web-crawling-in-java-a-tale-of-classical-threads-and-virtual-threads/
- https://medium.com/@RamLakshmanan/java-virtual-threads-easy-introduction-44d96b8270f8
- https://blog.rockthejvm.com/ultimate-guide-to-java-virtual-threads/

In this ticket Spring needs to be upgrade in Java 21 and the `asyncDiscordExecutor` needs to be updated to use Virtual Threads.
https://www.baeldung.com/spring-6-virtual-threads 

### Tasks

- [x] Update/Test the Spring core with Java 21
- [ ] Update Test @Async execution with Virtual Threads
- [x] Update CI to build the app in Java 21
- [x] Update AWS environments
- [ ]

**Comment by sekasx** [comment]
@myrtp please check this
