### ISSUE TITLE
As a back end developer, I want to implement the project agent's ai model, for semantic search and completion 

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#105]
## User Story

As a developer, I want to populate the `project_Agent.semantic_search_model_id` and `project_agent.completion_model_id` columns with the corresponding AI model names, Ada2 and gpt-3.5-turbo, respectively, for the `projectAgent` object when creating a new project. Additionally, I want to ensure that these values are idempotently populated in the existing data.

### Task 1: Update ProjectController of package controllers

- [x] In the `ProjectController` class, update the `createProject` method to set (using setters) the `semanticSearchModelId` and `completionModelId` values in the `projectAgent` object. This values are foreign keys in the `project_agent` table.

### Task 2: Create AiModelsConstants
Since in the database in the table ai_models at the moment we only have 3 models.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGV4QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ab3e92e2e10945c66409365ecf9b5e1b00edf330/image.png)

We will hardcode the values

- [x] Create a new class named `AiModelsConstants` in the `utils.constants` package, which should contain the names of the Ai models.
- [x] Define constants for the AI model names, such as `ADA2_MODEL` and `GPT_3_5_TURBO_MODEL`, in the `AiModelsConstants` class.

### Task 3: Populate Existing Data
Because there is already data in the project_agent data table, with no values ​​in the semantic_search_model_id and completion_model_id columns, we should populate them in an [Idempotent Database](https://docs.getdbt.com/terms/idempotent)
 way.

- [x] Ensure that existing data in the `project_agent` table has the `semantic_search_model_id` and `completion_model_id` columns populated idempotently with the corresponding AI model names, Ada2 and gpt-3.5-turbo, using the values from `AiModelsConstants`.
- [x] A sql file should be created, in the folder database.src.main.resources.db.migrations.gendox-core.

## Acceptance Criteria

- [x] The `createProject` method in `ProjectController` sets the `semanticSearchModelId` and `completionModelId` in the `projectAgent` object when creating a new project.
- [x] The `AiModelsConstants` class contains constants for the AI model names, Ada2 and gpt-3.5-turbo.
- [x] Existing data in the `project_agent` table has the `semantic_search_model_id` and `completion_model_id` columns populated idempotently with the corresponding AI model names.

## Definition of Done

- [x] The code is written and tested.
- [x] The `projectAgent` object is updated with the correct AI model names during project creation.
- [x] The existing data in the `project_agent` table is correctly populated with the AI model names.
- [x] The modifications are reviewed and approved.
- [x] The POST `http://localhost:8080/gendox/api/v1/projects` in Postman, works.
