### ISSUE TITLE
As a backend developer I want to Validate Subscription Plans

### ISSUE THREAD

**Issue by gyfantidis** [ctrl-space-labs/gendox-core#363]
**Task Title:**  
Validate SubscriptionPlan Attributes in Backend  

**Description:**  
Implement validation for all attributes of the `SubscriptionPlan` model to ensure data integrity and compliance with business rules. 

**Checklist:**  
- [ ] **Validation Rules:**  
  - [ ] Max messages per billing month 
  - [ ] Max Documents (file upload limit)
  - [ ] Max Sections
  - [ ] Max Integrations (Integration or websites)
  - [ ] Max invited people (Number of Seats)
  - [ ]
