### ISSUE TITLE
As a Backend developer I want to separate document upload from split functionality

### ISSUE THREAD

**Issue by sekasx** [ctrl-space-labs/gendox-core#94]
## User Story

As a Backend developer, I want to separate document upload from split functionality to improve code organization and maintainability.

## Task Description

The necessary processing will be done in the `uploadService` so that only the methods that are for the upload process remain. The rest of the methods will be moved to the new service called `splitFileService`.

A new method called `handleFileSplitter` will be added to the `documentController`. It will accept criteria and the ID of the project. The method will output a list of `documentInstanceSections`, which will be derived from the `splitFileService`.

I want upload file controllers to be separated and separate for Upload and separate for document separation.

## Acceptance Criteria

- The `uploadService` should be refactored to include only methods related to the upload process.
- A new service called `splitFileService` should be created to handle document separation functionality.
- The `documentController` should have a new method called `handleFileSplitter` that accepts criteria and project ID and returns a list of `documentInstanceSections`.
- The code should be organized in a way that separates upload and document separation concerns.

## Definition of Done

- The code changes are reviewed and approved.
- Unit tests for the new code are written and passing.
- Documentation is updated to reflect the changes.

## Tasks

- [x] Refactor `uploadService` to separate upload-related methods.
- [x] Create a new service called `splitFileService` to handle document separation.
- [x] Add a new method `handleFileSplitter` to the `documentController`.
- [x] Organize the code to separate upload and document separation concerns.
